main-build:
    docker:
        - image: connectedhomeip/chip-build-openssl:0.2.15
nrf-build:
    docker:
        - image: connectedhomeip/chip-build-nrf-platform:0.2.15
esp32-build:
    docker:
        - image: connectedhomeip/chip-build-esp32:0.2.15
esp32-qemu-build:
    docker:
        - image: connectedhomeip/chip-build-esp32-qemu:0.2.15
linux-embedded:
    environment:
        BOOTSTRAP_ARGUMENTS: " --with-device-layer=linux"
    docker:
        - image: connectedhomeip/chip-build:0.2.15
mbedtls-build:
    environment:
        BOOTSTRAP_ARGUMENTS: " --with-crypto=mbedtls"
    docker:
        - image: connectedhomeip/chip-build:0.2.15
clang-build:
    environment:
        BOOTSTRAP_ARGUMENTS: " CC=clang-9 CXX=clang++-9"
    docker:
        - image: connectedhomeip/chip-build:0.2.15
