# SPDX-FileCopyrightText: 2020 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

TestBeds:
    # A test bed where pw_rpc will find a CHIP device
    - Name: SampleTestBed
      Controllers:
          PigweedDevice:
              - device_tty: /dev/ttyACM0
                baud: 115200
