[pt_table]
#partition table is 4K in size
address0 = 0x1000
address1 = 0x2000

[[pt_entry]]
type = 0
name = "FW"
device = 0
address0 = 0x3000
size0 = 0x123000
address1 = 0x126000
size1 = 0xC4000
# compressed image must set len,normal image can left it to 0
len = 0
activeindex = 0
age = 0

[[pt_entry]]
type = 1
name = "mfg"
device = 0
address0 = 0x126000
size0 = 0xC4000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
activeindex = 0
age = 0

[[pt_entry]]
type = 2
name = "PSM"
device = 0
address0 = 0x1EA000
size0 = 0x10000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
activeindex = 0
age = 0

[[pt_entry]]
type = 3
name = "media"
device = 0
address0 = 0x1FA000
size0 = 0x4000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
activeindex = 0
age = 0

[[pt_entry]]
type = 4
name = "MFD"
device = 0
address0 = 0x1FE000
size0 = 0x1000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
activeindex = 0
age = 0

[[pt_entry]]
type = 5
name = "factory"
device = 0
address0 = 0x1FF000
size0 = 0x1000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
activeindex = 0
age = 0

