## IDF Component Manager Manifest File
dependencies:
    espressif/mdns:
        version: "^1.1.0"
        rules:
            - if: "idf_version >=5.0"
            - if: "target != esp32h2"

    espressif/esp_secure_cert_mgr:
        version: "^2.3.0"
        rules:
            - if: "idf_version >=4.3"

    espressif/esp_encrypted_img:
        version: "2.0.3"
        rules:
            - if: "idf_version >=4.4"
