# SPDX-FileCopyrightText: 2021 Project CHIP Authors
#
# SPDX-License-Identifier: Apache-2.0

TestBeds:
    # A test bed for esp32 where pw_rpc will find a CHIP device
    - Name: ESP32TestBed
      Controllers:
          PigweedDevice:
              - device_tty: /dev/ttyUSB1
                baud: 115200
                platform_module: esp32_firmware_utils
                platform_args:
                    - "application": "chip-pigweed-app.bin"
                      "parttool": None
                      "port": "/dev/ttyUSB0"
                      "baud": "921600"
                      "before": "default_reset"
                      "after": "hard_reset"
                      "flash_mode": "dio"
                      "flash_freq": "40m"
                      "flash_size": "2MB"
                      "compress": "y"
                      "bootloader": "bootloader/bootloader.bin"
                      "partition": "partitions.bin"
                      "partition_offset": "0x8000"
                      "application_offset": "0x10000"
