name: World Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Pretty Check
        run: |
          sudo apt install clang-format-9
          ./bootstrap
          make -f Makefile-Standalone pretty-check

      - name: Run Build
#        run: ./bootstrap && make -f Makefile-Standalone distcheck
        run: ./integrations/docker/docker_build.sh
