name: Build CI image - chip-build 
on:
  workflow_dispatch:
    inputs:
        mark_latest:
          description: 'Update latest to the current built version'
          required: true
          default: "true"

jobs:
    chip-build-cr:
        name: Build and push multi-arch 'chip-build' image
        runs-on: ubuntu-latest
        env:
            ARCH: "x86_64 aarch64"
            IMAGE_NAME: chip-build

        steps:
            - name: Prepare platform arguments
              run: |
                    tmp=(linux/${ARCH// /,linux/})
                    echo "DOCKER_BUILDX_PLATFORMS=$tmp" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 1
                  submodules: false

            - name: Get build version from file
              if: ${{ contains('false', github.event.inputs.mark_latest) }}
              run: echo "BUILD_VERSION=$(cat integrations/docker/images/${{ env.IMAGE_NAME }}/version)" >> $GITHUB_ENV
            
            - name: Set tag to 'latest'
              if: ${{ contains('true', github.event.inputs.mark_latest) }}
              run: echo "BUILD_VERSION=latest" >> $GITHUB_ENV

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
              with:
                image: tonistiigi/binfmt:latest
                platforms: ${{ env.DOCKER_BUILDX_PLATFORMS}}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: integrations/docker/images/${{ env.IMAGE_NAME }}
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
                platforms: ${{ env.DOCKER_BUILDX_PLATFORMS}}
