name: GN Examples

on:
    push:
    pull_request:

jobs:
    nrf:
        name: nRF

        env:
            BUILD_TYPE: nrf
            BUILD_VERSION: 0.2.14
            BUILD_IMAGE: chip-build-nrf-platform
            BUILD_ORG: connectedhomeip

        runs-on: ubuntu-latest

        container:
            image: connectedhomeip/chip-build-nrf-platform:0.2.14 # $BUILD_IMAGE/$BUILD_ORG:$BUILD_VERSION
            volumes:
                - "/tmp/bloat_reports:/tmp/bloat_reports"
                - "/tmp/output_binaries:/tmp/output_binaries"

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Checkout Submodules
              run: make -f Makefile-bootstrap repos
            - name: Bootstrap
              run: scripts/build/gn_bootstrap.sh
            - name: Build example nRF5 Lock App
              run: scripts/examples/gn_nrf_example.sh examples/lock-app/nrf5 out/lock_app_debug
            - name: Build example nRF5 Lighting App
              run: scripts/examples/gn_nrf_example.sh examples/lighting-app/nrf5 out/lighting_app_debug
            - name: Binary artifact suffix
              id: outsuffix
              uses: haya14busa/action-cond@v1.0.0
              with:
                  cond: ${{ github.event.pull_request.number == '' }}
                  if_true: "${{ github.sha }}"
                  if_false: "pull-${{ github.event.pull_request.number }}"
            - name: Uploading Binaries
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.BUILD_TYPE }}-example-build-${{ steps.outsuffix.outputs.value }}
                  path: |
                          out/lock_app_debug/chip-nrf52840-lock-example
                          out/lighting_app_debug/chip-nrf52840-lighting-example

    linux-standalone:
        name: Linux Standalone

        env:
            BUILD_TYPE: linux
            BUILD_VERSION: 0.2.14
            BUILD_IMAGE: chip-build
            BUILD_ORG: connectedhomeip

        runs-on: ubuntu-latest

        container:
            image: connectedhomeip/chip-build:0.2.14 # $BUILD_IMAGE/$BUILD_ORG:$BUILD_VERSION
            volumes:
                - "/tmp/bloat_reports:/tmp/bloat_reports"
                - "/tmp/output_binaries:/tmp/output_binaries"

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Checkout Submodules
              run: make -f Makefile-bootstrap repos
            - name: Bootstrap
              run: scripts/build/gn_bootstrap.sh
            - name: Build example Standalone Echo Client
              run: scripts/examples/gn_build_example.sh examples/chip-tool out/chip_tool_debug
            - name: Build example Standalone Shell
              run: scripts/examples/gn_build_example.sh examples/shell out/shell_debug
            - name: Binary artifact suffix
              id: outsuffix
              uses: haya14busa/action-cond@v1.0.0
              with:
                  cond: ${{ github.event.pull_request.number == '' }}
                  if_true: "${{ github.sha }}"
                  if_false: "pull-${{ github.event.pull_request.number }}"
            - name: Uploading Binaries
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.BUILD_TYPE }}-example-build-${{ steps.outsuffix.outputs.value }}
                  path: |
                          out/chip_tool_debug/chip-standalone-demo
                          out/shell_debug/chip-shell
