name: Manually Roll, Build, and Push Docker Images
on:
  workflow_dispatch:
jobs:
  roll_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Roll docker versions
        run: ./scripts/helpers/docker-version-roll.sh --reason="Automated roll by GitHub Action"
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Rolling Docker Version
