name: Create issues from todos

on:
  push:
    branches:
     - master

jobs:
  todos:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: todo-actions
          uses: dtinth/todo-actions@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
