name: Create issues from To-Dos

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: 'false'
        required: false
        type: boolean
        description: Enable, if you want to import all TODOs. Runs on checked out branch! Only use if you're sure what you are doing.
# Disabled until I can bootstrap the main ones
#   push:
#     branches: # do not set multiple branches, todos might be added and then get referenced by themselves in case of a merge
#       - main
#       - master

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todos:
    name: Scan for To-Dos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Issue Bot
        uses: derjuulsn/todo-issue@main
        with:
          autoAssign: false
# Label disabled until this works: https://github.com/DerJuulsn/todo-issue/issues/9
#           label: "todo"
          keywords: "todo,fixme,bug,TODO,FIXME,BUG"
          excludePattern: '^(node_modules/|third_party/|zzz_generated/|docs/|.vscode/)'
        env:
          GITHUB_TOKEN: ${{ secrets.MATTER_PAT }}
